import {test,expect,type Page} from "@playwright/test";
import fs from "node:fs";
const env=Object.fromEntries(fs.readFileSync(".env.local","utf8").split(/\r?\n/).filter(x=>x.includes("=")&&!x.startsWith("#")).map(x=>[x.slice(0,x.indexOf("=")),x.slice(x.indexOf("=")+1)]));
const fixture=JSON.parse(fs.readFileSync("../.private/fixture.json","utf8")) as {memberIds:string[];sessionId:string};
async function pair(page:Page,role:"kiosk"|"staff"){await page.goto("/integration/pair");await page.locator('select[name="role"]').selectOption(role);await page.locator('input[name="pairKey"]').fill(role==="kiosk"?env.DOJANG_KIOSK_PAIR_KEY:env.DOJANG_STAFF_PAIR_KEY);await page.getByRole("button",{name:"Connect device"}).click();await page.waitForURL(role==="kiosk"?"**/kiosk":"**/integration/members");}
async function selectStudent(page:Page,name:string){await page.goto("/kiosk");await page.getByRole("button",{name:/check in/i}).first().click();await page.getByRole("button").filter({hasText:"Demo session"}).first().click();const input=page.locator('input').first();await expect(input).toBeVisible();await input.fill(name);await page.getByRole("button").filter({hasText:name}).first().click();}

test('kiosk saves Odoo attendance and Member 360 reads the same result',async({browser})=>{const kiosk=await browser.newContext(),staff=await browser.newContext();const page=await kiosk.newPage(),view=await staff.newPage();await pair(page,"kiosk");await pair(view,"staff");const before=await view.request.get(`/api/v2/members/${fixture.memberIds[0]}`);expect(before.ok()).toBeTruthy();expect((await before.json()).attendance.lastSevenDays).toBe(0);await selectStudent(page,"Avery");const result=page.waitForResponse(r=>r.url().includes('/api/v2/attendance/check-ins')&&r.request().method()==='POST');await page.getByRole('button',{name:/confirm/i}).click();const response=await result;expect(response.ok()).toBeTruthy();const receipt=await response.json();expect(receipt.receipt.memberId).toBe(fixture.memberIds[0]);const after=await view.request.get(`/api/v2/members/${fixture.memberIds[0]}`);const data=await after.json();expect(data.attendance.lastSevenDays).toBe(1);expect(data.attendance.latest.checkedInAt).toBe(receipt.receipt.checkedInAt);await view.goto(`/people/${fixture.memberIds[0]}`);await expect(view.getByText('Verified attendance',{exact:true})).toBeVisible();await view.screenshot({path:'test-results/member360-connected.png',fullPage:true});await page.screenshot({path:'test-results/kiosk-receipt.png',fullPage:true});await expect(page.getByRole('button',{name:/check in/i}).first()).toBeVisible({timeout:30000});await expect(page.getByText('Avery D.',{exact:true})).toHaveCount(0);await kiosk.close();await staff.close();});

test('guided Companion reads Odoo and creates one reviewed real task',async({browser})=>{const ctx=await browser.newContext();const page=await ctx.newPage();await pair(page,'staff');await page.goto(`/integration/companion?memberId=${fixture.memberIds[0]}`);await page.getByRole('button',{name:'Read attendance summary'}).click();await expect(page.getByText(/Avery Demo: 1 check-ins/)).toBeVisible();await page.getByRole('button',{name:'Prepare follow-up task'}).click();await expect(page.getByRole('dialog')).toBeVisible();const wait=page.waitForResponse(r=>r.url().includes('/api/v2/companion/actions'));await page.getByRole('button',{name:'Approve and create task'}).click();const response=await wait;expect(response.ok()).toBeTruthy();const body=await response.json();expect(body.status).toBe('created');expect(body.messageSent).toBe(false);const original=response.request().postDataJSON();const replay=await page.request.post('/api/v2/companion/actions',{headers:{origin:'http://localhost:3000'},data:original});expect((await replay.json()).taskId).toBe(body.taskId);await page.screenshot({path:'test-results/companion-task-receipt.png',fullPage:true});await ctx.close();});

test('offline attendance is pending then replayed to Odoo once',async({browser})=>{const kiosk=await browser.newContext(),staff=await browser.newContext();const page=await kiosk.newPage(),view=await staff.newPage();await pair(page,'kiosk');await pair(view,'staff');await selectStudent(page,'Blake');await kiosk.setOffline(true);await page.getByRole('button',{name:/confirm/i}).click();await expect(page.getByText(/attendance request pending sync/)).toBeVisible();const before=await view.request.get(`/api/v2/members/${fixture.memberIds[1]}`);expect((await before.json()).attendance.lastSevenDays).toBe(0);await page.screenshot({path:'test-results/offline-pending.png',fullPage:true});await kiosk.setOffline(false);await expect.poll(async()=>{const r=await view.request.get(`/api/v2/members/${fixture.memberIds[1]}`);return (await r.json()).attendance.lastSevenDays;},{timeout:45000}).toBe(1);await expect(page.getByText(/attendance request pending sync/)).toHaveCount(0);await page.reload();await expect.poll(async()=>{const r=await view.request.get(`/api/v2/members/${fixture.memberIds[1]}`);return (await r.json()).attendance.lastSevenDays;}).toBe(1);await kiosk.close();await staff.close();});

test('unpaired device cannot read roster or execute a task',async({request})=>{expect((await request.get(`/api/v2/sessions/${fixture.sessionId}/roster`)).status()).toBe(403);expect((await request.post('/api/v2/companion/actions',{headers:{origin:'http://localhost:3000'},data:{memberId:fixture.memberIds[0],action:'attendance_summary'}})).status()).toBe(403);});
